In [1]:
data = {'Name': ["Tommy", "Linda", "Justin", "Brendon"],
        'Age': [31, 24, 16, 22]}

In [5]:
type(data)

dict

In [7]:
import pandas as pd
df = pd.DataFrame(data)
df

Name  Age
0    Tommy   31
1    Linda   24
2   Justin   16
3  Brendon   22

In [9]:
X = df['Name']
X

0      Tommy
1      Linda
2     Justin
3    Brendon
Name: Name, dtype: object

In [10]:
type(X)

pandas.core.series.Series

In [13]:
y = df ['Age']
y

0    31
1    24
2    16
3    22
Name: Age, dtype: int64

In [14]:
type(y)

pandas.core.series.Series

In [17]:
X1 = df.iloc[:, 0]
X1

0      Tommy
1      Linda
2     Justin
3    Brendon
Name: Name, dtype: object

In [18]:
type(X1)

pandas.core.series.Series

In [26]:
import numpy as np
X = np.zeros((4,10))
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
type(X)

numpy.ndarray

In [36]:
np.random.seed(555)
X = np.random.rand(4)
X

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [32]:
X[0][1]

0.1333129363807567

In [38]:
type(X)

numpy.ndarray

In [39]:
X.dtype

dtype('float64')

In [3]:
import torch
random_number= torch.rand(2,3)
random_number

tensor([[0.0206, 0.7779, 0.5342],
        [0.0605, 0.6420, 0.7559]])

In [6]:
random_number.ndim

2

In [8]:
random_number.shape

torch.Size([2, 3])

In [10]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.arange(1,4)

tensor([1, 2, 3])

In [15]:
x = torch.rand(3,2)
x

tensor([[0.7291, 0.1292],
        [0.6324, 0.0694],
        [0.0708, 0.1965]])

In [17]:
print(f"so the the output tensor is: {x}")

so the the output tensor is: tensor([[0.7291, 0.1292],
        [0.6324, 0.0694],
        [0.0708, 0.1965]])
