In [3]:
import torch
random_number= torch.rand(2,3)
random_number

tensor([[0.0206, 0.7779, 0.5342],
        [0.0605, 0.6420, 0.7559]])

In [6]:
random_number.ndim


2

In [8]:
random_number.shape

torch.Size([2, 3])

In [10]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.arange(1,4)

tensor([1, 2, 3])

In [15]:
x = torch.rand(3,2)
x

tensor([[0.7291, 0.1292],
        [0.6324, 0.0694],
        [0.0708, 0.1965]])

In [17]:
print(f"so the the output tensor is: {x}")

so the the output tensor is: tensor([[0.7291, 0.1292],
        [0.6324, 0.0694],
        [0.0708, 0.1965]])
