In [ ]:
data = {'Name': ["Tommy", "Linda", "Justin", "Brendon"],
        'Age': [31, 24, 16, 22]}

: 

In [2]:
type(data)

dict

In [3]:
import pandas as pd
df = pd.DataFrame(data)
df

Name  Age
0    Tommy   31
1    Linda   24
2   Justin   16
3  Brendon   22

In [4]:
X = df['Name']
X

0      Tommy
1      Linda
2     Justin
3    Brendon
Name: Name, dtype: object

In [5]:
type(X)

pandas.core.series.Series

In [6]:
y = df ['Age']
y

0    31
1    24
2    16
3    22
Name: Age, dtype: int64

In [7]:
type(y)

pandas.core.series.Series

In [8]:
X1 = df.iloc[:, 0]
X1

0      Tommy
1      Linda
2     Justin
3    Brendon
Name: Name, dtype: object

In [9]:
type(X1)

pandas.core.series.Series

In [10]:
import numpy as np
X = np.zeros((4,10))
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
type(X)

numpy.ndarray

In [12]:
np.random.seed(555)
X = np.random.rand(4,2)
X

array([[0.71783409, 0.04785513],
       [0.94447198, 0.68638004],
       [0.58120733, 0.14267862],
       [0.94591918, 0.33999059]])

In [13]:
X[0][1]

0.047855132556195557

In [14]:
type(X)

numpy.ndarray

In [15]:
X.dtype

dtype('float64')

In [16]:
X = np.array([1,2,3,4])
X.dtype

dtype('int32')

In [17]:
type(X)

numpy.ndarray

In [18]:
import torch
X = torch.from_numpy(X)
X.dtype

torch.int32

In [19]:
type(X)

torch.Tensor

In [20]:
X

tensor([1, 2, 3, 4], dtype=torch.int32)

In [21]:
y = torch.tensor(X)

C:\Users\rznis\AppData\Local\Temp\ipykernel_7908\3121897943.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(X)


In [22]:
y

tensor([1, 2, 3, 4], dtype=torch.int32)

In [23]:
X[0]=.4

In [24]:
X

tensor([0, 2, 3, 4], dtype=torch.int32)

In [25]:
y

tensor([1, 2, 3, 4], dtype=torch.int32)

In [26]:
torch.zeros(4,3,dtype=torch.int16)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)

In [27]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [28]:
x[1,1]

tensor(3)

In [29]:
import torch
random_number= torch.rand(2,3)
random_number

tensor([[0.2856, 0.5922, 0.8522],
        [0.7390, 0.0343, 0.9977]])

In [30]:
random_number.ndim

2

In [31]:
random_number.shape

torch.Size([2, 3])

In [32]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [33]:
torch.arange(1,4)

tensor([1, 2, 3])

In [34]:
x = torch.rand(3,2)
x

tensor([[0.2294, 0.5878],
        [0.0956, 0.0464],
        [0.3515, 0.2826]])

In [35]:
print(f"so the the output tensor is: {x}")

so the the output tensor is: tensor([[0.2294, 0.5878],
        [0.0956, 0.0464],
        [0.3515, 0.2826]])
